sylius_resource:
  resources:
    app.testimony:
      classes:
        model: Odiseo\SyliusTestimonyPlugin\Entity\Testimony
        form: Odiseo\SyliusTestimonyPlugin\Form\Type\TestimonyType
      translation:
        classes:
          model: Odiseo\SyliusTestimonyPlugin\Entity\TestimonyTranslation

sylius_grid:
  grids:
    app_admin_testimony:
      driver:
        name: doctrine/orm
        options:
          class: Odiseo\SyliusTestimonyPlugin\Entity\Testimony
      limits: [30, 12, 48]
      fields:
        title:
          type: string
          label: 'Title'
        description:
          type: string
        state:
          type: string
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete

winzou_state_machine:
  app_testimony:
    class: Odiseo\SyliusTestimonyPlugin\Entity\Testimony # class of your domain object
    property_path: state            # property of your object holding the actual state (default is "state")
    graph: app_testimony                   # name of the graph (default is "default")
    states:
      - pending_review
      - published
      - rejected
    transitions:
      publish:
        from: [pending_review]
        to: published
      reject:
        from: [pending_review]
        to: rejected
